import { useRef, useState } from 'react'
import { requestGate } from './admin-state.js'
const statuses = { active: '生效', pending: '待审核', disabled: '停用' }
const roles = { operator: '操作员', manager: '经理', admin: '管理员' }
const roleOptions = Object.entries(roles).map(([value, label]) => ({ value, label }))
function Status({ value }) { return <span className="admin-status-tag" data-status={value}>{statuses[value] || value}</span> }
export default function AdminDirectorySection({ governance, shared }) {
  const [form, setForm] = useState({ name: '', code: '' }); const [editing, setEditing] = useState(null); const [memberEditing, setMemberEditing] = useState(null); const [memberForm, setMemberForm] = useState({ displayName: '', role: 'operator' }); const [busy, setBusy] = useState(''); const [openStore, setOpenStore] = useState(''); const [details, setDetails] = useState({}); const [writeError, setWriteError] = useState(''); const gate = useRef(requestGate())
  const directory = governance?.directory || []
  if (!governance) return <section className="admin-panel"><h2>门店</h2><p className="admin-empty">暂无数据。</p></section>
  const submit = async (event) => { event.preventDefault(); setBusy('create'); try { await shared.createDirectory('stores', { name: form.name, code: form.code, status: 'active' }); setForm({ name: '', code: '' }) } catch (error) { setWriteError(error?.message || '操作失败，请重试。'); } finally { setBusy('') } }
  const rename = async (store) => { const name = editing?.name?.trim(); if (!name) return; setBusy('rename:' + store.id); try { await shared.updateDirectory('stores', store.id, { name, code: store.code, status: store.status }); setEditing(null) } catch (error) { setWriteError(error?.message || '操作失败，请重试。'); } finally { setBusy('') } }
  const toggle = async (store) => { if (store.status === 'pending') return; setBusy('toggle:' + store.id); try { await shared.updateDirectory('stores', store.id, { name: store.name, code: store.code, status: store.status === 'active' ? 'disabled' : 'active' }) } catch (error) { setWriteError(error?.message || '操作失败，请重试。'); } finally { setBusy('') } }
  const loadMembers = async (storeId) => { const request = gate.current.next(); setDetails((all) => ({ ...all, [storeId]: { busy: true } })); try { const payload = await shared.getStore(storeId, request.signal); if (gate.current.isLatest(request.id)) setDetails((all) => ({ ...all, [storeId]: { payload } })) } catch (error) { if (error.name !== 'AbortError' && gate.current.isLatest(request.id)) setDetails((all) => ({ ...all, [storeId]: { error: error.message } })) } }
  const viewMembers = (storeId) => { if (openStore === storeId) setOpenStore(''); else { setOpenStore(storeId); if (!details[storeId]) void loadMembers(storeId) } }
  const memberMutation = async (store, member, remove = false) => { if (remove && !window.confirm('确认从' + store.name + '移除成员“' + member.displayName + '”？')) return; setBusy('member:' + store.id); try { if (remove) await shared.removeMember(store.id, member.userId, { expectedUpdatedAt: member.updatedAt }); else await shared.updateMember(store.id, member.userId, { displayName: memberForm.displayName, role: memberForm.role, expectedUpdatedAt: member.updatedAt }); await loadMembers(store.id); setMemberEditing(null) } catch (error) { setWriteError(error?.message || '操作失败，请重试。'); } finally { setBusy('') } }
  const name = (store) => editing?.id === store.id ? <input className="admin-directory-rename" autoFocus value={editing.name} onChange={(event) => setEditing({ id: store.id, name: event.target.value })} onKeyDown={(event) => event.key === 'Enter' && void rename(store)} aria-label="门店名称" /> : <strong title={store.name}>{store.name}</strong>
  const actions = (store) => <div className="admin-directory-actions">{editing?.id === store.id ? <><button type="button" onClick={() => void rename(store)} disabled={busy === 'rename:' + store.id}>保存</button><button type="button" onClick={() => setEditing(null)}>取消</button></> : <button type="button" aria-label={"重命名" + store.name} onClick={() => setEditing({ id: store.id, name: store.name })}>重命名</button>}{store.status !== 'pending' ? <button type="button" aria-label={(store.status === 'active' ? '停用' : '启用') + store.name} onClick={() => void toggle(store)} disabled={busy === 'toggle:' + store.id}>{store.status === 'active' ? '停用' : '启用'}</button> : null}</div>
  const memberPanel = (store) => { const state = details[store.id] || {}; if (state.busy) return <div className="admin-directory-member-panel"><p className="admin-status">正在读取成员…</p></div>; if (state.error) return <div className="admin-directory-member-panel"><p className="form-error">{state.error}</p></div>; const members = state.payload?.members || []; return <div className="admin-directory-member-panel"><div className="admin-directory-member-list">{!members.length ? <p className="admin-empty">暂无已注册成员。</p> : members.map((member) => memberEditing?.userId === member.userId ? <div key={member.userId} className="admin-directory-member-row admin-directory-member-edit"><input value={memberForm.displayName} onChange={(event) => setMemberForm({ ...memberForm, displayName: event.target.value })} aria-label="成员姓名" /><select value={memberForm.role} onChange={(event) => setMemberForm({ ...memberForm, role: event.target.value })} aria-label="成员角色">{roleOptions.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select><button type="button" onClick={() => void memberMutation(store, member)}>保存</button><button type="button" onClick={() => setMemberEditing(null)}>取消</button></div> : <div key={member.userId} className="admin-directory-member-row"><strong>{member.displayName}{member.isPlatformAdmin ? <span className="admin-platform-badge">平台管理员</span> : null}</strong><span>{member.username}</span><span>{roles[member.role] || member.role}</span><Status value={member.status} />{member.isPlatformAdmin ? null : <><button type="button" onClick={() => { setMemberEditing({ userId: member.userId }); setMemberForm({ displayName: member.displayName, role: member.role }) }}>编辑</button><button type="button" onClick={() => void memberMutation(store, member, true)}>移除</button></>}</div>)}</div></div> }
  return <section className="admin-panel"><header className="admin-panel-head"><h2>门店</h2><small>DIRECTORY · 平面门店目录</small></header><form className="data-form admin-directory-form" onSubmit={submit}><label className="field-row"><span>门店代码</span><input required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value })} /></label><label className="field-row"><span>门店名称</span><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><button type="submit" className="primary-action" disabled={busy === 'create'}>新增门店</button></form>{writeError ? <p className="form-error admin-directory-write-error" role="alert">{writeError}</p> : null}<div className="admin-directory-waterfall"><div className="admin-directory-major-grid">{directory.map((store) => <div key={store.id} className="admin-directory-store-block"><div className="admin-directory-store-row"><span className="admin-directory-store-identity"><span className="admin-store-code">{store.code}</span>{name(store)}</span><Status value={store.status} /><span className="admin-directory-member-count">成员 {store.memberCount || 0} 人</span><div className="admin-directory-actions"><button type="button" aria-label={(openStore === store.id ? '收起' : '查看') + store.name + '成员'} onClick={() => viewMembers(store.id)}>{openStore === store.id ? '收起' : '查看'}</button>{actions(store)}</div></div>{openStore === store.id ? memberPanel(store) : null}</div>)}</div></div></section>
}
