import { useEffect, useRef, useState } from 'react'
import AppDialog from '../dialogs/AppDialog.jsx'
import ProjectSelect from '../ProjectSelect.jsx'
import { idempotencyKey } from '../../api/client.js'
import { appendUniqueById, requestGate } from './admin-state.js'
const roleLabels = { operator: '操作员', manager: '经理', admin: '管理员' }
const roleOptions = [{ value: 'operator', label: '操作员' }, { value: 'manager', label: '经理' }, { value: 'admin', label: '管理员' }]
function formatTime(value) { if (!value) return '—'; const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : new Intl.DateTimeFormat('zh-CN', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(date) }
export default function AdminUsersSection({ shared, stores = [] }) {
  const [query, setQuery] = useState(''); const [data, setData] = useState({ users: [] }); const [nextCursor, setNextCursor] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const [createOpen, setCreateOpen] = useState(false); const [confirmToggle, setConfirmToggle] = useState(null); const [confirmReset, setConfirmReset] = useState(null); const [resetResult, setResetResult] = useState(null); const gateRef = useRef(requestGate())
  const load = async (q, cursor = '', append = false) => { const request = gateRef.current.next(); setBusy(true); setError(''); try { const result = await shared.getUsers({ q, cursor }, request.signal); if (!gateRef.current.isLatest(request.id)) return; setData((current) => ({ users: append ? appendUniqueById(current.users, result.users) : result.users })); setNextCursor(result.nextCursor) } catch (requestError) { if (requestError.name !== 'AbortError' && gateRef.current.isLatest(request.id)) setError(requestError.message || '无法读取用户列表。') } finally { if (gateRef.current.isLatest(request.id)) setBusy(false) } }
  useEffect(() => { void load(''); return () => gateRef.current.cancel() }, [])
  const mutate = async (work, after) => { setBusy(true); setError(''); try { const result = await work(); await load(query.trim()); await shared.refreshSummary(); after?.(result); return true } catch (requestError) { setError(requestError.message || '操作失败，请重试。'); return false } finally { setBusy(false) } }
  const doToggle = async () => { const user = confirmToggle; if (!user) return; const ok = await mutate(() => shared.toggleUserStatus(user, user.status === 'active' ? 'disabled' : 'active')); if (ok) setConfirmToggle(null) }
  const doReset = async () => { const state = confirmReset; if (!state) return; const ok = await mutate(() => shared.resetPassword(state.user, state.key), (result) => setResetResult({ user: state.user, tempPassword: result.tempPassword })); if (ok) setConfirmReset(null) }
  return <section className="admin-panel"><header className="admin-panel-head"><h2>用户与成员</h2><small>USERS · 全平台账号与门店角色</small></header><form className="admin-toolbar" role="search" onSubmit={(event) => { event.preventDefault(); void load(query.trim()) }}><label><span className="sr-only">搜索用户</span><input type="search" placeholder="搜索姓名或登录名" maxLength="80" value={query} onChange={(event) => setQuery(event.target.value)} /></label><button type="submit" className="secondary-action">搜索</button><button type="button" className="primary-action admin-toolbar-primary" onClick={() => setCreateOpen(true)}>创建账号</button>{busy ? <span className="admin-inline-status" role="status">处理中…</span> : null}</form>{error ? <p className="form-error" role="alert">{error}</p> : null}
    <div className="admin-table-wrap admin-desktop-table"><table className="admin-table"><thead><tr><th>用户</th><th>登录名</th><th>角色</th><th>门店</th><th>状态</th><th>最近登录</th><th>操作</th></tr></thead><tbody>{data.users.map((user) => <tr key={user.id}><td><strong>{user.displayName}</strong>{user.isPlatformAdmin ? <span className="admin-platform-badge">平台管理员</span> : null}</td><td><span className="admin-username">{user.username}</span></td><td>{user.memberships.map((m) => roleLabels[m.role] || m.role).join('、') || '—'}</td><td>{user.memberships.map((m) => `${m.storeCode} ${m.storeName}`).join('、') || '—'}</td><td><span className="admin-status-tag" data-status={user.status}>{user.status === 'active' ? '生效' : '停用'}</span></td><td>{formatTime(user.lastLoginAt)}</td><td><UserActions user={user} busy={busy} onToggle={setConfirmToggle} onReset={(target) => setConfirmReset({ user: target, key: idempotencyKey() })} /></td></tr>)}</tbody></table></div>
    <div className="admin-mobile-cards">{data.users.map((user) => <article key={user.id} className="admin-mobile-card"><header><strong>{user.displayName}</strong><span className="admin-status-tag" data-status={user.status}>{user.status === 'active' ? '生效' : '停用'}</span></header><p className="admin-username">{user.username}</p><dl><div><dt>角色</dt><dd>{user.memberships.map((m) => roleLabels[m.role] || m.role).join('、') || '—'}</dd></div><div><dt>门店</dt><dd>{user.memberships.map((m) => `${m.storeCode} ${m.storeName}`).join('、') || '—'}</dd></div><div><dt>最近登录</dt><dd>{formatTime(user.lastLoginAt)}</dd></div></dl>{user.isPlatformAdmin ? <span className="admin-platform-badge">平台管理员 · 受保护</span> : <UserActions user={user} busy={busy} onToggle={setConfirmToggle} onReset={(target) => setConfirmReset({ user: target, key: idempotencyKey() })} />}</article>)}</div>
    {!data.users.length && !busy ? <p className="admin-empty">没有匹配的用户。</p> : null}{nextCursor ? <button type="button" className="secondary-action admin-load-more" disabled={busy} onClick={() => void load(query.trim(), nextCursor, true)}>加载更多用户</button> : null}
    {createOpen ? <CreateUserDialog shared={shared} stores={stores} onClose={() => setCreateOpen(false)} onCreated={async () => { setCreateOpen(false); await load(query.trim()); await shared.refreshSummary() }} /> : null}
    {confirmToggle ? <ConfirmDialog title={confirmToggle.status === 'active' ? '禁用账号' : '恢复账号'} description={`${confirmToggle.displayName} · ${confirmToggle.username}`} busy={busy} danger={confirmToggle.status === 'active'} warning={confirmToggle.status === 'active' ? '禁用后该账号所有已登录会话将立即失效。' : '恢复后该账号可重新登录，原会话不会自动恢复。'} onClose={() => setConfirmToggle(null)} onConfirm={() => void doToggle()} /> : null}
    {confirmReset ? <ConfirmDialog title="重置密码" description={`${confirmReset.user.displayName} · ${confirmReset.user.username}`} busy={busy} danger warning="重置后现有会话立即失效；临时密码只显示一次。" onClose={() => setConfirmReset(null)} onConfirm={() => void doReset()} /> : null}
    {resetResult ? <TempPasswordDialog result={resetResult} onClose={() => setResetResult(null)} /> : null}
  </section>
}
function UserActions({ user, busy, onToggle, onReset }) { return <div className="admin-row-actions">{user.isPlatformAdmin ? <span className="admin-inline-status">受保护</span> : <><button type="button" className="secondary-action" disabled={busy} onClick={() => onToggle(user)}>{user.status === 'active' ? '禁用' : '恢复'}</button><button type="button" className="secondary-action" disabled={busy || user.status !== 'active'} onClick={() => onReset(user)}>重置密码</button></>}</div> }
function ConfirmDialog({ title, description, warning, busy, danger, onClose, onConfirm }) { return <AppDialog open onClose={onClose} dismissible={!busy} title={title} eyebrow="CONFIRM · 受审计" description={description} className="admin-confirm-dialog"><p className="admin-warning">{warning}</p><div className="admin-decision-actions"><button type="button" className="secondary-action" disabled={busy} onClick={onClose}>取消</button><button type="button" className="primary-action" data-danger={danger ? 'true' : undefined} disabled={busy} onClick={onConfirm}>{busy ? '处理中…' : `确认${title}`}</button></div></AppDialog> }
function TempPasswordDialog({ result, onClose }) { const [copied, setCopied] = useState(false); const copy = async () => { try { await navigator.clipboard.writeText(result.tempPassword); setCopied(true) } catch { setCopied(false) } }; return <AppDialog open onClose={onClose} dismissible={false} title="一次性临时密码" eyebrow="ONE-TIME · 仅显示一次" description={`${result.user.displayName} · ${result.user.username}`} className="admin-temp-dialog"><p className="admin-temp-password">{result.tempPassword}</p><p className="admin-warning">请复制并安全转交；对方下次登录将被强制修改密码。</p><div className="admin-decision-actions"><button type="button" className="secondary-action" onClick={() => void copy()}>{copied ? '已复制' : '复制临时密码'}</button><button type="button" className="primary-action" disabled={!copied} onClick={onClose}>已安全转交，关闭</button></div></AppDialog> }
function CreateUserDialog({ shared, stores, onClose, onCreated }) { const [form, setForm] = useState({ username: '', displayName: '', storeId: '', role: 'operator', password: '', confirmPassword: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const requestRef = useRef({ key: idempotencyKey(), signature: '' }); const submit = async (event) => { event.preventDefault(); if (!form.storeId) return setError('请选择门店。'); if (form.password !== form.confirmPassword) return setError('两次输入的密码不一致。'); const body = { username: form.username, displayName: form.displayName, storeId: form.storeId, role: form.role, password: form.password }; const signature = JSON.stringify(body); if (requestRef.current.signature !== signature) requestRef.current = { key: idempotencyKey(), signature }; setBusy(true); setError(''); try { await shared.createUser(body, requestRef.current.key); await onCreated() } catch (requestError) { setError(requestError.message || '创建账号失败。') } finally { setBusy(false) } }; return <AppDialog open onClose={onClose} dismissible={!busy} title="创建账号" eyebrow="CREATE USER · 受审计" description="登录名与全系统契约一致，最多 24 个字符；新账号首次登录强制改密。"><form className="data-form" onSubmit={submit}><label className="field-row"><span>登录名</span><input data-autofocus required maxLength="24" value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /></label><label className="field-row"><span>姓名</span><input required maxLength="24" value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} /></label><label className="field-row"><span>门店</span><ProjectSelect value={form.storeId} options={stores} onChange={(storeId) => setForm({ ...form, storeId })} ariaLabel="选择门店" /></label><label className="field-row"><span>角色</span><ProjectSelect value={form.role} options={roleOptions} onChange={(role) => setForm({ ...form, role })} ariaLabel="选择角色" /></label><label className="field-row"><span>初始密码</span><input required type="password" minLength="10" maxLength="128" autoComplete="new-password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label><label className="field-row"><span>确认密码</span><input required type="password" minLength="10" maxLength="128" autoComplete="new-password" value={form.confirmPassword} onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })} /></label>{error ? <p className="form-error" role="alert">{error}</p> : null}<div className="admin-decision-actions"><button type="button" className="secondary-action" disabled={busy} onClick={onClose}>取消</button><button type="submit" className="primary-action" disabled={busy}>{busy ? '创建中…' : '创建账号'}</button></div></form></AppDialog> }
