-- Split the single Guangxi city into three real cities: Nanning, Guilin, Liuzhou.
-- Target directory shape: 南区 -> 广西江湖区 -> 南宁 (1670, 1299) / 桂林 (994) / 柳州 (1249).
--
-- Safety properties this migration must keep (see packages/database/test/directory-cities.test.mjs):
--   * Store 1299 is the only store carrying real production data. It is never written by this file.
--   * The existing Guangxi city row is RENAMED IN PLACE so its id stays stable and the stores
--     already pointing at it (1670, 1299) need no write at all.
--   * Every new city inherits a concrete subregion_id. governance.ts joins subregions with an
--     INNER JOIN, so a city with a NULL subregion_id would silently vanish from the directory.
--   * Store reassignment uses literal city ids plus an EXISTS guard, never a bare subquery that
--     could evaluate to NULL and blank out stores.city_id.
--   * Forward-only and idempotent: no DELETE, no DROP, no ALTER. Re-running writes nothing.

-- 1. Rename Guangxi -> Nanning in place. The id is untouched, so no store row moves.
--    Guarded against a pre-existing Nanning row in the same region (UNIQUE (region_id, normalized_name)).
UPDATE cities
SET name = '南宁',
    normalized_name = '南宁',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '30000000-0000-4000-8000-000000000002'
  AND normalized_name = '广西'
  AND NOT EXISTS (
    SELECT 1 FROM cities other
    WHERE other.region_id = cities.region_id
      AND other.normalized_name = '南宁'
      AND other.id <> cities.id
  );

-- 2. Add Guilin. subregion_id/region_id are inherited from the Nanning row so the new city lands in
--    the same 广西江湖区 subtree regardless of how subregion ids were generated by 0009.
INSERT INTO cities (id, region_id, name, normalized_name, status, sort_order, created_at, updated_at, subregion_id)
SELECT '50000000-0000-4000-8000-000000000001', base.region_id, '桂林', '桂林', 'active', 20,
       strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), base.subregion_id
FROM cities base
WHERE base.id = '30000000-0000-4000-8000-000000000002'
  AND base.subregion_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM cities dup
    WHERE dup.region_id = base.region_id AND dup.normalized_name = '桂林'
  );

-- 3. Add Liuzhou, same rules as Guilin.
INSERT INTO cities (id, region_id, name, normalized_name, status, sort_order, created_at, updated_at, subregion_id)
SELECT '50000000-0000-4000-8000-000000000002', base.region_id, '柳州', '柳州', 'active', 30,
       strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), base.subregion_id
FROM cities base
WHERE base.id = '30000000-0000-4000-8000-000000000002'
  AND base.subregion_id IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM cities dup
    WHERE dup.region_id = base.region_id AND dup.normalized_name = '柳州'
  );

-- 4. Move 994 穿山店 to Guilin. Literal target id + EXISTS guard: if step 2 did not create the city
--    this statement matches no rows instead of writing a NULL city_id.
UPDATE stores
SET city_id = '50000000-0000-4000-8000-000000000001',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE code = '994'
  AND (city_id IS NULL OR city_id <> '50000000-0000-4000-8000-000000000001')
  AND EXISTS (SELECT 1 FROM cities c WHERE c.id = '50000000-0000-4000-8000-000000000001');

-- 5. Move 1249 河东店 to Liuzhou, same rules as 994.
UPDATE stores
SET city_id = '50000000-0000-4000-8000-000000000002',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE code = '1249'
  AND (city_id IS NULL OR city_id <> '50000000-0000-4000-8000-000000000002')
  AND EXISTS (SELECT 1 FROM cities c WHERE c.id = '50000000-0000-4000-8000-000000000002');
