import IconBell from '@iconoir/Bell.mjs'
import IconMenu from '@iconoir/Menu.mjs'
import { APP_VERSION } from '../../data/releaseNotes.js'
import { sceneById } from '../../data/lookbookScenes.js'

export default function WorkshopShellHeader({ activeScene, storeName, roleLabel, userName, onMenu, onLog, onHome, hasUnread }) {
  const scene = sceneById(activeScene)
  if (scene.id === 'pulse') return <header className="workshop-shell-header" data-active-module={scene.id} aria-label={`${storeName || '门店'} · ${roleLabel || '成员'} · ${userName || '—'} · V${APP_VERSION}`}><div className="workshop-poster-header"><div className="workshop-poster-brand"><i aria-hidden="true"><b /><b /><b /></i><span>WORKSHOP OPERATIONS</span></div><button type="button" className="workshop-poster-coordinate" onClick={onLog} aria-label="查看当日日志"><b aria-hidden="true">+</b><span>22°32′ / 113°56′</span>{hasUnread ? <i aria-hidden="true" /> : null}</button><button type="button" className="workshop-poster-menu" onClick={onMenu} aria-label="打开日报菜单"><span>MENU</span><IconMenu width={19} height={19} aria-hidden="true" /></button></div></header>
  return <header className="workshop-shell-header workshop-static-header" data-active-module={scene.id}><div className="workshop-static-header-row"><button type="button" className="workshop-static-menu" onClick={onMenu} aria-label="打开日报菜单"><IconMenu width={30} height={30} aria-hidden="true" /></button><button type="button" className="workshop-static-brand" onClick={onHome} aria-label="返回总览"><span>WORKSHOP LEDGER</span><strong>WORKSHOP OPS</strong><small>V{APP_VERSION}</small></button><button type="button" className="workshop-static-log" onClick={onLog} aria-label="查看当日日志"><IconBell width={31} height={31} aria-hidden="true" />{hasUnread ? <i aria-hidden="true" /> : null}</button><div className="workshop-static-module"><span><small>{scene.label}</small><strong>{scene.cn}</strong><b>{scene.title}</b></span><em>{scene.no} / 06</em></div></div><span className="sr-only">{storeName || '门店'} · {roleLabel || '成员'} · {userName || '—'}</span></header>
}
